import type { Metadata } from 'next'
import '../../app/globals.css'
import { ContextProvider } from '../../contextAPI/context'
import { AuthStoreProvider } from '@/stores/auth/auth.provider'
import { AuthWrapper } from './(components)/auth-wrapper'
import React from 'react'

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const metadata: Metadata = {
  title: 'WGL APP | Portal',
  description: 'Generated by create next app',
}

export default function PortalLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <AuthStoreProvider>
      <ContextProvider>
        <AuthWrapper>{children}</AuthWrapper>
      </ContextProvider>
    </AuthStoreProvider>
  )
}
